<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="FastEndpoints.Testing" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Endatix.Modules.Jobs\Endatix.Modules.Jobs.csproj" />
  </ItemGroup>

</Project>
