# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=5001
@apiBaseUrl = {{host}}:{{port}}/api
@jwt = {{login.response.body.token}}
@formId = 1263081289527853056
@validUsername=developer@endatix.com
@validPassword=P@$$word1

// Register user
# @name register
POST {{apiBaseUrl}}/auth/register
Content-Type: application/json

{
    "email": "developer@endatix.com",
    "password": "P@$$word1",
    "confirmPassword": "P@$$word1"
}

###
// Login to obtain JWT Token
# @name login
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
    "email": "developer@endatix.com",
    "password": "P@$$word1"
}

###
// List all forms
GET {{apiBaseUrl}}/forms
Authorization: Bearer {{jwt}}

###
// Get all form definitions
GET {{apiBaseUrl}}/forms/{{formId}}/definitions
Authorization: Bearer {{jwt}}

###
// List all submissions by Form Id
GET {{apiBaseUrl}}/forms/{{formId}}/submissions?page=1&pageSize=10
Authorization: Bearer {{jwt}}