# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=5001
@apiBaseUrl = {{host}}:{{port}}/api
@jwt = {{login.response.body.$.accessToken}}
@formId = 1263081289527853056
@validEmail=user@example.com
@validPassword=Password123!

// Register user
# @name register
POST {{apiBaseUrl}}/auth/register
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "{{validPassword}}",
    "confirmPassword": "{{validPassword}}"
}

###
// Login to obtain JWT Token
# @name login
POST {{apiBaseUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "{{validPassword}}"
}

###
// Refresh JWT token
# @name refresh
POST {{apiBaseUrl}}/auth/refresh-token
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "refreshToken": "example-refresh-token"
}

###
// Logout an authenticated user
# @name logout
POST {{apiBaseUrl}}/auth/logout
Authorization: Bearer {{jwt}}
Content-Type: application/json

###
// List all forms
GET {{apiBaseUrl}}/forms
Authorization: Bearer {{jwt}}

###
// Get all form definitions
GET {{apiBaseUrl}}/forms/{{formId}}/definitions
Authorization: Bearer {{jwt}}

###
// List all submissions by Form Id
GET {{apiBaseUrl}}/forms/{{formId}}/submissions?page=1&pageSize=10
Authorization: Bearer {{jwt}}
