-- =============================================
-- Function: export_form_submissions
-- Description: Exports form submissions with answers structured as a JSON model.
--              Optimized to use a correlated subquery for aggregation (avoids CROSS JOIN explosion).
--              Supports keyset pagination for large datasets.
-- Parameters: form_id - The ID of the form to export
--             after_id - Optional cursor (return rows with Id > after_id)
--             page_size - Optional limit (NULL = all)
-- Returns: Table with submission details and structured answers
-- Database: PostgreSQL
-- =============================================

CREATE OR REPLACE FUNCTION export_form_submissions(form_id bigint, after_id bigint DEFAULT NULL, page_size int DEFAULT NULL)
RETURNS TABLE (
    "FormId" bigint,
    "Id" bigint,
    "IsComplete" boolean,
    "CompletedAt" timestamptz,
    "CreatedAt" timestamptz,
    "ModifiedAt" timestamptz,
    "AnswersModel" jsonb
) AS $$
BEGIN
    RETURN QUERY
    -- Recursive CTE to extract all form elements including nested panels
    WITH RECURSIVE element_tree AS (
        -- Base case: Get top-level elements from form pages
        SELECT elem AS element
        FROM "FormDefinitions" fd,
             jsonb_array_elements(fd."JsonData" -> 'pages') AS page,
             jsonb_array_elements(page->'elements') AS elem
        WHERE fd."FormId" = export_form_submissions.form_id
          AND fd."JsonData" ? 'pages'

        UNION ALL

        -- Recursive case: Get elements from nested panels
        SELECT jsonb_array_elements(element -> 'elements') AS element
        FROM element_tree
        WHERE (element->>'type') = 'panel'
    ),
    -- Extract unique question names from all elements (excluding panels)
    question_names AS (
        SELECT DISTINCT element->>'name' AS name
        FROM element_tree
        WHERE (element->>'type') IS DISTINCT FROM 'panel'
          AND element ? 'name'
    ),
    -- Combine submission data with answers for each question.
    -- Optimized: Uses a correlated subquery to build the JSON object per submission.
    -- This avoids the O(N*M) intermediate rows generated by CROSS JOIN + GROUP BY.
    submission_fields AS (
        SELECT
            s."Id",
            s."FormId",
            s."IsComplete",
            s."CompletedAt",
            s."CreatedAt",
            s."ModifiedAt",
            (
                SELECT jsonb_object_agg(q.name, COALESCE(s."JsonData" -> q.name, '""'::jsonb))
                FROM question_names q
            ) AS AnswersModel
        FROM "Submissions" s
        WHERE s."FormId" = export_form_submissions.form_id
          AND (export_form_submissions.after_id IS NULL OR s."Id" > export_form_submissions.after_id)
    )
    -- Final selection of all submission fields
    SELECT
        sf."FormId",
        sf."Id",
        sf."IsComplete",
        sf."CompletedAt",
        sf."CreatedAt",
        sf."ModifiedAt",
        sf.AnswersModel
    FROM submission_fields sf
    ORDER BY sf."Id"
    LIMIT export_form_submissions.page_size;
END;
$$ LANGUAGE plpgsql;
