import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Endatix Form",
  description: "Generated by Endatix",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {children}
    </div>
  );
}
