name: First Contribution

on:
  issues:
    types: opened
  pull_request:
    types: opened

permissions:
  pull-requests: write
  issues: write

jobs:
  welcome-message:
    name: Send welcome messages to new contributors
    runs-on: ubuntu-latest
    timeout-minutes: 12
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Thank you so much for submitting your first Pull Request and contributing to Endatix! 🚀 🖖 😻
            Your work helps us towards our mission of improving how data is collected, managed, and processed. You are a hero! 🥷

            A core team member will review your pull request shortly.
            Please feel welcome to join us for discussion on [Discord](https://discord.gg/VPqzMJgS). We’d love to chat with you!

            If you haven't already, please take a moment to review our [contribution guide](https://docs.endatix.com/docs/intro). This guide provides helpful information to ensure your contribution aligns with our standards.
          issue-message: |
            Thank you for submitting your first issue, this is just awesome! 🚀 🖖 😻
            We will review it and get back to you as soon as possible.

            In the meantime, please take a moment to complete the template, if you haven't done so yet. This ensures that we fully understand your feature request or bug report. For more details on what happens next, please check out our [documentation](https://docs.endatix.com/docs/intro).

            Thanks again for your contribution! We appreciate your support in making our project better.
